<?php
namespace exface\UI5Facade\Facades\Elements;

use exface\Core\Facades\AbstractAjaxFacade\Elements\LeafletTrait;
use exface\UI5Facade\Facades\Elements\Traits\UI5DataElementTrait;
use exface\Core\Widgets\Data;
use exface\UI5Facade\Facades\Interfaces\UI5ControllerInterface;
use exface\Core\DataTypes\StringDataType;
use exface\Core\Widgets\Parts\Maps\DataSelectionMarkerLayer;
use exface\Core\Interfaces\Widgets\iUseData;
use exface\Core\CommonLogic\DataSheets\DataColumn;
use exface\Core\Factories\WidgetFactory;
use exface\Core\Widgets\Parts\Maps\Interfaces\LatLngWidgetLinkMapLayerInterface;

/**
 * 
 * @method exface\Core\Widgets\Chart getWidget()
 * @method UI5ControllerInterface getController()
 * 
 * @author Andrej Kabachnik
 *
 */
class UI5Map extends UI5AbstractElement
{
    use LeafletTrait, UI5DataElementTrait {
        LeafletTrait::buildJsValueGetter insteadof UI5DataElementTrait;
        LeafletTrait::buildJsDataGetter insteadof UI5DataElementTrait;
        UI5DataElementTrait::buildJsGetSelectedRows insteadof LeafletTrait;
        UI5DataElementTrait::buildJsDataLoaderParams as buildJsDataLoaderParamsViaTrait;
    }
    
    private $leafletVarTemp = null;
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\UI5Facade\Facades\Elements\UI5AbstractElement::buildJsConstructor()
     */
    public function buildJsConstructorForControl($oControllerJs = 'oController') : string
    {
        $this->initLeaflet();
        $mapWidget = $this->getWidget();
        
        $this->getConfiguratorElement()->registerFiltersWithApplyOnChange($this);
        
        $controller = $this->getController(); 
        $this->registerExternalModules($controller);
        $this->registerLiveReferenceAtLinkedElements();
        $this->getController()->addOnPrefillDataChangedScript($this->buildJsRefresh());
        
        // Add a single data loader controller method for all layers. However, give it an additional
        // parameter oLeafletParams so each layer can override request params if needed. The content
        // of the method will be generated by the UI5DataElementTrait, but at some point it will call
        // `buildJsDataLoaderParams()` where we will place the logic to handle oLeafletParams.
        $controller->addMethod('onLoadData', $this, 'oControlEvent, bKeepPagingPos, oLeafletParams', $this->buildJsDataLoader());
        
        $leafletVarJs = $controller->buildJsObjectName('leaflet', $this);
        
        // Make sure buildJsLeafletVar() returns oController.xxx to maximize performance
        // because many initialization scripts require the leaflet variable and would
        // otherwise run all the logic to find the component, the controller, etc.
        $this->leafletVarTemp = 'oController.' . $leafletVarJs;
        
        if ($mapWidget->isCenterBoundToAttributes()) {
            $centerLatCol = DataColumn::sanitizeColumnName($mapWidget->getCenterLatitudeAttributeAlias());
            $centerLngCol = DataColumn::sanitizeColumnName($mapWidget->getCenterLongitudeAttributeAlias());
            $controller->addOnPrefillDataChangedScript(<<<JS
                
                setTimeout(function(){
                    var oPrefillData = {$controller->getView()->buildJsViewGetter($this)}.getModel().getData();
                    var lat = oPrefillData['{$centerLatCol}'];
                    var lng = oPrefillData['{$centerLngCol}'];
                    if (! isNaN(lat) && ! isNaN(lng)) {
                        {$this->buildJsLeafletVar($oControllerJs)}.setView([lat, lng]);
                    }
                }, 0);
                
JS);
        }
        
        // **IMPORTANT:** it seems, an outer div with the id of the control is required because
        // otherwise the map is not rendered at all after navigating to a view via routing. The map
        // gets rendered even before the view is shown, but once the view is visible, the leaflet-div
        // is empty while the leaflet-var is initialized, which is very strange.
        // I guess, this has something to do with the so-called "preserved content" of sap.ui.core.HTML 
        // (see for an explanation for possible causes: https://github.com/SAP/openui5/issues/1162).
        $chart = <<<JS

                new sap.ui.core.HTML("{$this->getId()}", {
                    content: "<div id=\"{$this->getId()}\" style=\"height: 100%;\"><div id=\"{$this->getIdLeaflet()}\" class=\"{$this->buildCssElementClass()}\" style=\"height: 100%; min-height: 100px; overflow: hidden;\"></div></div>",
                    afterRendering: function(oEvent) { 
                        if (oController.$leafletVarJs === null || oController.$leafletVarJs === undefined) {  
                            {$this->buildJsLeafletInit()};     
                        } 

                        sap.ui.core.ResizeHandler.register(sap.ui.getCore().byId('{$this->getId()}').getParent(), function(){
                            if (oController.$leafletVarJs) {
                                {$this->buildJsLeafletResize()}
                            }
                        });

                        sap.ui.getCore().byId('{$this->getId()}').getParent().addStyleClass('sapUiNoContentPadding');
                    }
                })

JS;
        // Remove the precalculated var name after init scripts were generated (see above).
        $this->leafletVarTemp = null;
        
        foreach ($this->getWidget()->getLayers() as $layer) {
            if ($layer instanceof LatLngWidgetLinkMapLayerInterface) {
                if (($linkLat = $layer->getLatitudeWidgetLink()) && ($linkLng = $layer->getLongitudeWidgetLink())) {
                    $this->getFacade()->getElement($linkLat->getTargetWidget())->addOnChangeScript($this->buildJsRefresh());
                    $this->getFacade()->getElement($linkLng->getTargetWidget())->addOnChangeScript($this->buildJsRefresh());
                }
            }
        }
                        
        return $this->buildJsPanelWrapper($chart, $oControllerJs);
    }
    
    /**
     * When the data loader calls buildJsDataLoaderParams() we need to extend extend
     * the default request parameters with those passed to the onLoadData...() method
     * by the respective layer. This is done here.
     * 
     * @see UI5DataElementTrait::buildJsDataLoaderParams()
     */
    protected function buildJsDataLoaderParams(string $oControlEventJsVar = 'oControlEvent', string $oParamsJs = 'params', $keepPagePosJsVar = 'bKeepPagingPos') : string
    {
        return $this->buildJsDataLoaderParamsViaTrait($oControlEventJsVar, $oParamsJs, $keepPagePosJsVar) . <<<JS

            $oParamsJs = $.extend(true, $oParamsJs, oLeafletParams);

JS;
    }
    
    protected function buildJsLeafletDataLoader(string $oRequestParamsJs, string $aResultRowsJs, string $onLoadedJs) : string
    {
        return <<<JS

        {$this->getController()->buildJsMethodCallFromController('onLoadData', $this, "null, null, $oRequestParamsJs")}
        .then(function(oModel) {
            var $aResultRowsJs = oModel.getData().rows || [];

            $onLoadedJs
        })

JS;
    }
    
    public function getIdLeaflet() : string
    {
        return $this->getId() . '_leaflet';
    }
    
    public function buildJsLeafletVar(string $oControllerJs = null) : string
    {
        if ($this->leafletVarTemp !== null) {
            return $this->leafletVarTemp;
        }
        $controller = $this->getController();
        if (! $controller->hasDependent('leaflet', $this)) {
            $controller->addProperty($controller->buildJsObjectName('leaflet', $this), 'null');
        }
        return $controller->buildJsDependentObjectGetter('leaflet', $this, $oControllerJs);
    }
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\UI5Facade\Facades\Elements\UI5AbstractElement::registerExternalModules()
     */
    public function registerExternalModules(UI5ControllerInterface $controller) : UI5AbstractElement
    {
        $f = $this->getFacade();
        $mainSrc = $f->buildUrlToSource('LIBS.LEAFLET.JS');
        $controller->addExternalModule('libs.exface.leaflet', $mainSrc, null, 'L');
        
        foreach ($this->getJsIncludes() as $src) {
            if ($src === $mainSrc) {
                continue;
            }
            $name = StringDataType::substringAfter($src, '/', $src, false, true);
            $name = str_replace('-', '_', $name);
            
            $name = 'libs.exface.leaflet.' . $name;
            $controller->addExternalModule($name, $src);
        }
        
        foreach ($this->getCssIncludes() as $src) {
            $controller->addExternalCss($src);
        }
        
        foreach ($this->getWidget()->getDataLayers() as $layer) {
            foreach ($layer->getDataWidget()->getColumns() as $col) {
                $f->getElement($col)->registerExternalModules($controller);
            }
        }
        return $this;
    }
        
    /**
     * 
     * @return array
     */
    protected function getJsIncludes() : array
    {
        $htmlTagsArray = $this->buildHtmlHeadTagsLeaflet();
        $tags = implode('', $htmlTagsArray);
        $jsTags = [];
        preg_match_all('#<script[^>]*src="([^"]*)"[^>]*></script>#is', $tags, $jsTags);
        return $jsTags[1];
    }
    
    /**
     *
     * @return array
     */
    protected function getCssIncludes() : array
    {
        $htmlTagsArray = $this->buildHtmlHeadTagsLeaflet();
        $tags = implode('', $htmlTagsArray);
        $jsTags = [];
        preg_match_all('#<link[^>]*href="([^"]*)"[^>]*/?>#is', $tags, $jsTags);
        return $jsTags[1];
    }
        
    /**
     *
     * {@inheritDoc}
     * @see exface\Core\Facades\AbstractAjaxFacade\Elements\LeafletTrait::buildJsRefresh()
     */
    public function buildJsRefresh(bool $keepPagingPosition = false) : string
    {
        return $this->buildJsLeafletRefresh();
    }
    
    /**
     * 
     * @see UI5DataElementTrait
     */
    protected function getDataWidget() : Data
    {
        $layer = $this->getWidget()->getDataLayers()[0];
        if ($layer) {
            return $layer->getDataWidget();
        }
        return WidgetFactory::create($this->getWidget()->getPage(), 'Data', $this->getWidget());
    }
    
    /**
     * {@inheritdoc}
     * @see \exface\UI5Facade\Facades\Elements\Traits\UI5DataElementTrait::buildJsShowMessageOverlay()
     */
    protected function buildJsShowMessageOverlay(string $message) : string
    {
        return '';
    }
    
    /**
     *
     * {@inheritdoc}
     * @see UI5DataElementTrait::buildJsOfflineHint()
     */
    protected function buildJsOfflineHint(string $oTableJs = 'oTable') : string
    {
        return '';
    }
    
    /**
     * 
     * @see UI5DataElementTrait::isEditable()
     */
    protected function isEditable()
    {
        return false;
    }
    
    /**
     * 
     * @see UI5DataElementTrait::buildJsGetSelectedRows()
     */
    protected function buildJsGetSelectedRows(string $oControlJs) : string
    {
        return $this->buildJsLeafletGetSelectedRows();
    }
    
    /**
     * @see UI5DataElementTrait
     */
    protected function hasPaginator() : bool
    {
        return false;
    }
    
    /**
     * @see UI5DataElementTrait
     */
    protected function hasQuickSearch() : bool
    {
        return false;
    }
    
    /**
     *
     * @see LeafletTrait::registerLiveReferenceAtLinkedElements()
     */
    protected function registerLiveReferenceAtLinkedElements()
    {
        foreach ($this->getWidget()->getLayers() as $layer) {
            if (($layer instanceof iUseData) && $link = $layer->getDataWidgetLink()) {
                $linked_element = $this->getFacade()->getElement($link->getTargetWidget());
                if ($linked_element) {
                    if ($layer instanceof DataSelectionMarkerLayer) {
                        $linked_element->addOnSelectScript($this->buildJsLeafletRefresh());
                    } else {
                        $linked_element->addOnRefreshScript($this->buildJsLeafletRefresh());
                    }
                }
            }
        }
        return $this;
    }
}