<?php
namespace exface\UI5Facade\Facades\Elements;

use exface\Core\Facades\AbstractAjaxFacade\Elements\LeafletTrait;
use exface\UI5Facade\Facades\Elements\Traits\UI5DataElementTrait;
use exface\Core\Widgets\Data;
use exface\UI5Facade\Facades\Interfaces\UI5ControllerInterface;
use exface\Core\DataTypes\StringDataType;

/**
 * 
 * @method exface\Core\Widgets\Chart getWidget()
 * @method UI5ControllerInterface getController()
 * 
 * @author Andrej Kabachnik
 *
 */
class UI5Map extends UI5AbstractElement
{
    use LeafletTrait, UI5DataElementTrait {
        LeafletTrait::buildJsValueGetter insteadof UI5DataElementTrait;
        LeafletTrait::buildJsDataGetter insteadof UI5DataElementTrait;
        UI5DataElementTrait::buildJsGetSelectedRows insteadof LeafletTrait;
        UI5DataElementTrait::buildJsDataLoaderParams as buildJsDataLoaderParamsViaTrait;
    }
    
    private $leafletVarTemp = null;
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\UI5Facade\Facades\Elements\UI5AbstractElement::buildJsConstructor()
     */
    public function buildJsConstructorForControl($oControllerJs = 'oController') : string
    {
        $this->initLeaflet();
        
        $this->getConfiguratorElement()->registerFiltersWithApplyOnChange($this);
        
        $controller = $this->getController(); 
        $this->registerExternalModules($controller);
        
        // Add a single data loader controller method for all layers. However, give it an additional
        // parameter oLeafletParams so each layer can override request params if needed. The content
        // of the method will be generated by the UI5DataElementTrait, but at some point it will call
        // `buildJsDataLoaderParams()` where we will place the logic to handle oLeafletParams.
        $controller->addMethod('onLoadData', $this, 'oControlEvent, bKeepPagingPos, oLeafletParams', $this->buildJsDataLoader());
        
        $leafletVarJs = $controller->buildJsObjectName('leaflet', $this);
        
        // Make sure buildJsLeafletVar() returns oController.xxx to maximize performance
        // because many initialization scripts require the leaflet variable and would
        // otherwise run all the logic to find the component, the controller, etc.
        $this->leafletVarTemp = 'oController.' . $leafletVarJs;
        $chart = <<<JS

                new sap.ui.core.HTML("{$this->getId()}", {
                    content: "<div id=\"{$this->getIdLeaflet()}\" class=\"{$this->buildCssElementClass()}\" style=\"height: 100%; min-height: 100px; overflow: hidden;\"></div>",
                    afterRendering: function(oEvent) { 
                        if (oController.$leafletVarJs === null || oController.$leafletVarJs === undefined) {  
                            {$this->buildJsLeafletInit()};     
                        }                

                        sap.ui.core.ResizeHandler.register(sap.ui.getCore().byId('{$this->getId()}').getParent(), function(){
                            {$this->buildJsLeafletResize()}
                        });

                        sap.ui.getCore().byId('{$this->getId()}').getParent().addStyleClass('sapUiNoContentPadding');
                    }
                })

JS;
        // Remove the precalculated var name after init scripts were generated (see above).
        $this->leafletVarTemp = null;
                        
        return $this->buildJsPanelWrapper($chart, $oControllerJs);
    }
    
    /**
     * When the data loader calls buildJsDataLoaderParams() we need to extend extend
     * the default request parameters with those passed to the onLoadData...() method
     * by the respective layer. This is done here.
     * 
     * @see UI5DataElementTrait::buildJsDataLoaderParams()
     */
    protected function buildJsDataLoaderParams(string $oControlEventJsVar = 'oControlEvent', string $oParamsJs = 'params', $keepPagePosJsVar = 'bKeepPagingPos') : string
    {
        return $this->buildJsDataLoaderParamsViaTrait($oControlEventJsVar, $oParamsJs, $keepPagePosJsVar) . <<<JS

            $oParamsJs = $.extend(true, $oParamsJs, oLeafletParams);

JS;
    }
    
    protected function buildJsLeafletDataLoader(string $oRequestParamsJs, string $aResultRowsJs, string $onLoadedJs) : string
    {
        return <<<JS

        {$this->getController()->buildJsMethodCallFromController('onLoadData', $this, "null, null, $oRequestParamsJs")}
        .then(function(oModel) {
            var $aResultRowsJs = oModel.getData().rows || [];

            $onLoadedJs
        })

JS;
    }
    
    public function getIdLeaflet() : string
    {
        return $this->getId() . '_leaflet';
    }
    
    public function buildJsLeafletVar(string $oControllerJs = null) : string
    {
        if ($this->leafletVarTemp !== null) {
            return $this->leafletVarTemp;
        }
        $controller = $this->getController();
        if (! $controller->hasDependent('leaflet', $this)) {
            $controller->addProperty($controller->buildJsObjectName('leaflet', $this), 'null');
        }
        return $controller->buildJsDependentObjectGetter('leaflet', $this, $oControllerJs);
    }
    
    /**
     * 
     * {@inheritDoc}
     * @see \exface\UI5Facade\Facades\Elements\UI5AbstractElement::registerExternalModules()
     */
    public function registerExternalModules(UI5ControllerInterface $controller) : UI5AbstractElement
    {
        $f = $this->getFacade();
        $mainSrc = $f->buildUrlToSource('LIBS.LEAFLET.JS');
        $controller->addExternalModule('libs.exface.leaflet', $mainSrc, null, 'L');
        
        foreach ($this->getJsIncludes() as $src) {
            if ($src === $mainSrc) {
                continue;
            }
            $name = StringDataType::substringAfter($src, '/', $src, false, true);
            $name = str_replace('-', '_', $name);
            
            $name = 'libs.exface.leaflet.' . $name;
            $controller->addExternalModule($name, $src);
        }
        
        foreach ($this->getCssIncludes() as $src) {
            $controller->addExternalCss($src);
        }
        
        foreach ($this->getWidget()->getDataLayers() as $layer) {
            foreach ($layer->getDataWidget()->getColumns() as $col) {
                $f->getElement($col)->registerExternalModules($controller);
            }
        }
        return $this;
    }
        
    /**
     * 
     * @return array
     */
    protected function getJsIncludes() : array
    {
        $htmlTagsArray = $this->buildHtmlHeadTagsLeaflet();
        $tags = implode('', $htmlTagsArray);
        $jsTags = [];
        preg_match_all('#<script[^>]*src="([^"]*)"[^>]*></script>#is', $tags, $jsTags);
        return $jsTags[1];
    }
    
    /**
     *
     * @return array
     */
    protected function getCssIncludes() : array
    {
        $htmlTagsArray = $this->buildHtmlHeadTagsLeaflet();
        $tags = implode('', $htmlTagsArray);
        $jsTags = [];
        preg_match_all('#<link[^>]*href="([^"]*)"[^>]*/?>#is', $tags, $jsTags);
        return $jsTags[1];
    }
        
    /**
     *
     * {@inheritDoc}
     * @see exface\Core\Facades\AbstractAjaxFacade\Elements\LeafletTrait::buildJsRefresh()
     */
    public function buildJsRefresh() : string
    {
        return $this->buildJsLeafletRefresh();
    }
    
    /**
     * 
     * @see UI5DataElementTrait
     */
    protected function getDataWidget() : Data
    {
        return $this->getWidget()->getDataLayers()[0]->getDataWidget();
    }
    
    /**
     * {@inheritdoc}
     * @see \exface\UI5Facade\Facades\Elements\Traits\UI5DataElementTrait::buildJsShowMessageOverlay()
     */
    protected function buildJsShowMessageOverlay(string $message) : string
    {
        return '';
    }
    
    /**
     *
     * {@inheritdoc}
     * @see UI5DataElementTrait::buildJsOfflineHint()
     */
    protected function buildJsOfflineHint(string $oTableJs = 'oTable') : string
    {
        return '';
    }
    
    /**
     * 
     * @see UI5DataElementTrait::isEditable()
     */
    protected function isEditable()
    {
        return false;
    }
    
    /**
     * 
     * @see UI5DataElementTrait::buildJsGetSelectedRows()
     */
    protected function buildJsGetSelectedRows(string $oControlJs) : string
    {
        return $this->buildJsLeafletGetSelectedRows();
    }
    
    /**
     * @see UI5DataElementTrait
     */
    protected function hasPaginator() : bool
    {
        return false;
    }
    
    /**
     * @see UI5DataElementTrait
     */
    protected function hasQuickSearch() : bool
    {
        return false;
    }
}